version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: risikoapp_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: risikoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - risikoapp_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: risikoapp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@risikoapp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - risikoapp_network

volumes:
  postgres_data:

networks:
  risikoapp_network:
    driver: bridge